services:
  db:
    image: postgres:17
    container_name: payment
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "tg_payment"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot:/root
